# Generated by Django 4.1.3 on 2022-11-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='desc',
            field=models.CharField(default='desc', max_length=2000),
            preserve_default=False,
        ),
    ]
